((cperl-mode . ((cperl-indent-level . 2)
                (cperl-continued-statement-offset . 2)
                (cperl-continued-brace-offset . 0)
                (cperl-close-paren-offset . -2)
                (cperl-indent-subs-specially . nil)
                (indent-tabs-mode . nil))))
