=head1 NAME 

DBIx::Class::Manual::FAQ - Frequently Asked Questions

=head1 QUESTIONS 

=head2 What is the point of this module? Is it a fork of Class::DBI?

=head2 Who's the intended audience for this module?

=head2 What databases does it support?

=head2 What's the current status of this module?

=head2 What's planned in the future?

=head2 Where can I go for support?

=cut

